version: "3.8"

services:
  docker-log-outside-container:
    container_name: docker-log-outside-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
